Do not pin markdown version, latest DRF version expects a newer version.
======================================================================
ERROR: test_html_rendering (tests.rest_framework.test_integration.IntegrationTestFiltering)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hsmett/Workspace/django-filter/tests/rest_framework/test_integration.py", line 287, in test_html_rendering
    response = view(request).render()
  File "/home/hsmett/.virtualenvs/django-filter/lib/python3.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/hsmett/.virtualenvs/django-filter/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/hsmett/.virtualenvs/django-filter/lib/python3.7/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/hsmett/.virtualenvs/django-filter/lib/python3.7/site-packages/rest_framework/renderers.py", line 686, in get_context
    'description': self.get_description(view, response.status_code),
  File "/home/hsmett/.virtualenvs/django-filter/lib/python3.7/site-packages/rest_framework/renderers.py", line 601, in get_description
    return view.get_view_description(html=True)
  File "/home/hsmett/.virtualenvs/django-filter/lib/python3.7/site-packages/rest_framework/views.py", line 245, in get_view_description
    return func(self, html)
  File "/home/hsmett/.virtualenvs/django-filter/lib/python3.7/site-packages/rest_framework/views.py", line 61, in get_view_description
    return formatting.markup_description(description)
  File "/home/hsmett/.virtualenvs/django-filter/lib/python3.7/site-packages/rest_framework/utils/formatting.py", line 63, in markup_description
    description = apply_markdown(description)
  File "/home/hsmett/.virtualenvs/django-filter/lib/python3.7/site-packages/rest_framework/compat.py", line 156, in apply_markdown
    md_filter_add_syntax_highlight(md)
  File "/home/hsmett/.virtualenvs/django-filter/lib/python3.7/site-packages/rest_framework/compat.py", line 213, in md_filter_add_syntax_highlight
    md.preprocessors.register(CodeBlockPreprocessor(), 'highlight', 40)
AttributeError: 'OrderedDict' object has no attribute 'register'